url: https://kooplex.github.io/
baseurl: 

# Site settings
title: Kooplex website
email: kooplex@complex.elte.hu
description: "For collaborative research and education."


# Team names, titles and social links
people:
- name: David Visontai
  pic: 1
  position: Lead Singer
  social:
    - title: github
      url: https://github.com/jegesm

- name: Jozsef Steger
  pic: 2
  position: Lead Drummer
  social:
    - title: github
      url: https://github.com/stegerjozsef

- name: Igor Carnaúba
  pic: 3
  position: Lead Vocalist
  social:
    - title: github
      url: https://github.com/stegerjozsef

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/kooplex

# Postal address (add as many lines as necessary)
address:
  - line: 1/A Pázmány Péter stny.
  - line: 1117 Budapest, Hungary

# Build settings
markdown: kramdown
permalink: pretty
